import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from './Sidebar'
import AppContextProvider from './states/context/AppContextProvider'
import RootHead from './RootHead'
import AuthContextProvider from './states/context/AuthContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider>
          <AuthContextProvider>
            <div className="App">
              <div className="Body-Wrapper">
                <RootHead></RootHead>
                <SideBar />
                <div className="Item-Section">{children}</div>
              </div>
            </div>
          </AuthContextProvider>
        </AppContextProvider>
      </body>
    </html>
  )
}
